Repository exoego/scala-js-nodejs, pull requests merged in 2020-02, with the labels that each got.

#152 Update sbt to 1.3.8
  project/build.properties
Labels: chore

#154 Automatic merging for dependencies update
  .mergify.yml
Labels: chore

#159 Drop JDK 8 since recent Scala 2.12/2.13 has no issue on JDK 11
  .travis.yml
Labels: chore

#160 Bump node.js versions
  .node-version
  .travis.yml
Labels: chore

#161 Fix "errors" module-related issues
  app/current/src/main/scala/io/scalajs/nodejs/Error.scala
  app/current/src/main/scala/io/scalajs/nodejs/SystemError.scala
Labels: bug

#162 Update scalatest to 3.1.1
  project/Dependencies.scala
Labels: chore

#156 Prepare cross-publishing for Scala.js
  .travis.yml
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/buffer/BufferTest.scala
  project/Dependencies.scala
  project/MySettings.scala
  project/plugins.sbt
  script/release.js
Labels: enhancement

#163 Use GH actions to speedup CI
  .github/workflows/format.yml
  .travis.yml
Labels: chore

#166 Fix key object in crypto module
  app/current/src/main/scala/io/scalajs/nodejs/crypto/Crypto.scala
  app/current/src/main/scala/io/scalajs/nodejs/crypto/KeyObject.scala
Labels: bug

#164 Added Github Actions status check
  .mergify.yml
Labels: chore

#165 Add Fs.opendir and Fs.Dir
  app/current/src/main/scala/io/scalajs/nodejs/fs/Fs.scala
  app/current/src/main/scala/io/scalajs/nodejs/fs/package.scala
  app/current/src/test/scala/io/scalajs/nodejs/fs/FsAsyncTest.scala
  app/current/src/test/scala/io/scalajs/nodejs/fs/FsClassesTest.scala
Labels: enhancement

#167 Fix wrong typing in events.EventEmitter
  app/current/src/main/scala/io/scalajs/nodejs/events/EventEmitter.scala
Labels: bug

#168 Those modules do not extend EventEmitter actually
  app/current/src/main/scala/io/scalajs/nodejs/Assert.scala
  app/current/src/main/scala/io/scalajs/nodejs/events/EventEmitter.scala
  app/current/src/main/scala/io/scalajs/nodejs/fs/Fs.scala
  app/current/src/main/scala/io/scalajs/nodejs/net/Net.scala
  app/current/src/main/scala/io/scalajs/nodejs/readline/Readline.scala
  app/current/src/main/scala/io/scalajs/nodejs/repl/REPL.scala
  app/current/src/main/scala/io/scalajs/nodejs/url/URL.scala
  app/current/src/main/scala/io/scalajs/nodejs/zlib/Zlib.scala
Labels: bug

#169 Buffer instance does not have kMaxLength actually
  app/current/src/main/scala/io/scalajs/nodejs/buffer/Buffer.scala
  app/current/src/main/scala/io/scalajs/nodejs/buffer/package.scala
Labels: bug

#171 Drop those deprecated in v0.9.x
  app/current/src/main/scala/io/scalajs/nodejs/stream/Stream.scala
Labels: chore

#170 Deprecate confusing extension to Buffer object
  app/current/src/main/scala/io/scalajs/nodejs/buffer/package.scala
Labels: enhancement

#172 Drop those deprecated in Node.js v8
  app/current/src/main/scala/io/scalajs/nodejs/console_module/Console.scala
Labels: chore

#174 Mark members deprecated in Node.js v13
  app/current/src/main/scala/io/scalajs/nodejs/http/ClientRequest.scala
  app/current/src/main/scala/io/scalajs/nodejs/http/ServerResponse.scala
Labels: chore

#173 Added Node.js v12 new members
  app/current/src/main/scala/io/scalajs/nodejs/http/ClientRequest.scala
  app/current/src/main/scala/io/scalajs/nodejs/http/ServerResponse.scala
  app/current/src/main/scala/io/scalajs/nodejs/http2/Http2ServerRequest.scala
  app/current/src/main/scala/io/scalajs/nodejs/http2/Http2ServerResponse.scala
  app/current/src/main/scala/io/scalajs/nodejs/stream/Stream.scala
  app/current/src/main/scala/io/scalajs/nodejs/tls/TLSSocket.scala
Labels: enhancement

#175 Agent should extend EventEmitter
  app/current/src/main/scala/io/scalajs/nodejs/http/Agent.scala
Labels: enhancement

#176 Overhaul event handler exntensions
  app/current/src/main/scala/io/scalajs/nodejs/child_process/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/cluster/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/dgram/Socket.scala
  app/current/src/main/scala/io/scalajs/nodejs/dgram/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/events/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/fs/FSWatcher.scala
  app/current/src/main/scala/io/scalajs/nodejs/fs/ReadStream.scala
  app/current/src/main/scala/io/scalajs/nodejs/fs/WriteStream.scala
  app/current/src/main/scala/io/scalajs/nodejs/http/Agent.scala
  app/current/src/main/scala/io/scalajs/nodejs/http/ClientRequest.scala
  app/current/src/main/scala/io/scalajs/nodejs/http/IncomingMessage.scala
  app/current/src/main/scala/io/scalajs/nodejs/http/Server.scala
  app/current/src/main/scala/io/scalajs/nodejs/http/ServerResponse.scala
  app/current/src/main/scala/io/scalajs/nodejs/http/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/http2/Http2ServerRequest.scala
  app/current/src/main/scala/io/scalajs/nodejs/http2/Http2ServerResponse.scala
  app/current/src/main/scala/io/scalajs/nodejs/http2/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/net/Server.scala
  app/current/src/main/scala/io/scalajs/nodejs/net/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/process/Process.scala
  app/current/src/main/scala/io/scalajs/nodejs/process/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/readline/Interface.scala
  app/current/src/main/scala/io/scalajs/nodejs/repl/REPLServer.scala
  app/current/src/main/scala/io/scalajs/nodejs/repl/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/stream/Stream.scala
  app/current/src/main/scala/io/scalajs/nodejs/tls/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/tty/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/zlib/package.scala
Labels: enhancement

#178 Naming all extension methods as ~Extensions
  app/current/src/main/scala/io/scalajs/nodejs/child_process/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/cluster/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/dgram/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/fs/ReadStream.scala
  app/current/src/main/scala/io/scalajs/nodejs/fs/WriteStream.scala
  app/current/src/main/scala/io/scalajs/nodejs/http/IncomingMessage.scala
  app/current/src/main/scala/io/scalajs/nodejs/http/Server.scala
  app/current/src/main/scala/io/scalajs/nodejs/http2/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/readline/Interface.scala
  app/current/src/main/scala/io/scalajs/nodejs/stream/Stream.scala
  app/current/src/main/scala/io/scalajs/nodejs/stream/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/tls/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/tty/WriteStream.scala
  app/current/src/main/scala/io/scalajs/nodejs/tty/package.scala
  app/current/src/main/scala/io/scalajs/util/NodeJSConverters.scala
Labels: chore

#177 Deprecate helper method unrelated to nodejs
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/TestHelper.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/child_process/ChildProcessTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/fs/FsTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/os/OSTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/url/URLObjectTest.scala
  core/src/main/scala/io/scalajs/util/DateHelper.scala
  core/src/main/scala/io/scalajs/util/JSONHelper.scala
  core/src/main/scala/io/scalajs/util/ScalaJsHelper.scala
Labels: chore

#179 Move implicit classes to package object so companion can be js.Object
  app/current/src/main/scala/io/scalajs/nodejs/fs/FSWatcher.scala
  app/current/src/main/scala/io/scalajs/nodejs/fs/ReadStream.scala
  app/current/src/main/scala/io/scalajs/nodejs/fs/WriteStream.scala
  app/current/src/main/scala/io/scalajs/nodejs/fs/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/http/Agent.scala
  app/current/src/main/scala/io/scalajs/nodejs/http/ClientRequest.scala
  app/current/src/main/scala/io/scalajs/nodejs/http/IncomingMessage.scala
  app/current/src/main/scala/io/scalajs/nodejs/http/Server.scala
  app/current/src/main/scala/io/scalajs/nodejs/http/ServerResponse.scala
  app/current/src/main/scala/io/scalajs/nodejs/http/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/readline/Interface.scala
  app/current/src/main/scala/io/scalajs/nodejs/readline/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/stream/Stream.scala
  app/current/src/main/scala/io/scalajs/nodejs/stream/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/timers/Immediate.scala
  app/current/src/main/scala/io/scalajs/nodejs/timers/Interval.scala
  app/current/src/main/scala/io/scalajs/nodejs/timers/Timeout.scala
  app/current/src/main/scala/io/scalajs/nodejs/timers/package.scala
  app/current/src/main/scala/io/scalajs/util/NodeJSConverters.scala
Labels: chore

#180 Implement OS.constants
  app/current/src/main/scala/io/scalajs/nodejs/child_process/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/os/OS.scala
  app/current/src/main/scala/io/scalajs/nodejs/os/OSConstants.scala
  app/current/src/test/scala/io/scalajs/nodejs/os/OSTest.scala
Labels: enhancement

#181 Expose disconnect/send on sub type of ChildProcess
  app/current/src/main/scala/io/scalajs/nodejs/child_process/ChildProcess.scala
Labels: enhancement

#184 Trivial cleanup
  app/current/src/main/scala/io/scalajs/nodejs/console_module/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/dns/PromisesResolver.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/fs/FsClassesTest.scala
Labels: chore

#182 Implement Process.features
  app/current/src/main/scala/io/scalajs/nodejs/process/Process.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/process/ProcessTest.scala
Labels: enhancement

#183 crypto.Certificate class is not recommended to be newed
  app/current/src/main/scala/io/scalajs/nodejs/crypto/Certificate.scala
  app/current/src/main/scala/io/scalajs/nodejs/crypto/Crypto.scala
Labels: chore

#186 Release/v0.10.0
  README.md
  script/release.js
  script/release.sh
  version.sbt
Labels: chore

#187 Fix freaky test
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/tty/TTYTest.scala
Labels: chore

#188 Remove deprecated library things (not deprecated in Node.js)
  app/current/src/main/scala/io/scalajs/nodejs/buffer/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/os/OSConstants.scala
  app/current/src/main/scala/io/scalajs/nodejs/process/Process.scala
  app/current/src/main/scala/io/scalajs/nodejs/process/package.scala
  app/current/src/main/scala/io/scalajs/util/NodeJSConverters.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/buffer/BufferTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/child_process/ChildProcessTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/fs/FsTest.scala
  core/src/main/scala/io/scalajs/util/DateHelper.scala
  core/src/main/scala/io/scalajs/util/JSONHelper.scala
  core/src/main/scala/io/scalajs/util/ScalaJsHelper.scala
Labels: chore

#189 Correct publishing settings
  build.sbt
Labels: chore
