Repository exoego/scala-js-nodejs, pull requests merged in 2020-01, with the labels that each got.

#139 Update sbt to 1.3.6
  project/build.properties
Labels: chore

#140 Update node version
  .node-version
  .travis.yml
Labels: chore

#141 Fix #110: setReadableEncoding should be readableEncoding
  app/current/src/main/scala/io/scalajs/nodejs/stream/Stream.scala
  app/current/src/test/scala/io/scalajs/nodejs/stream/ReadableTest.scala
Labels: bug

#142 Release 0.9.1
  README.md
  version.sbt
Labels: chore

#145 Use js.BigInt
  app/current/src/main/scala/io/scalajs/nodejs/buffer/Buffer.scala
  app/current/src/main/scala/io/scalajs/nodejs/fs/Fs.scala
  app/current/src/main/scala/io/scalajs/nodejs/fs/Stats.scala
  app/current/src/main/scala/io/scalajs/nodejs/fs/package.scala
  app/current/src/main/scala/io/scalajs/nodejs/process/Process.scala
  app/current/src/test/scala/io/scalajs/nodejs/buffer/BufferTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/process/ProcessTest.scala
Labels: enhancement

#146 Remove unused variable
  app/current/src/main/scala/io/scalajs/nodejs/fs/package.scala
Labels: chore

#147 Migrate to scalatest new fashion
  app/current/src/test/scala/io/scalajs/nodejs/TopLevelTest.scala
  app/current/src/test/scala/io/scalajs/nodejs/buffer/BufferTest.scala
  app/current/src/test/scala/io/scalajs/nodejs/fs/FsAsyncTest.scala
  app/current/src/test/scala/io/scalajs/nodejs/fs/FsClassesTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/AssertTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/StringDecoderTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/assertion/AssertTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/buffer/BufferTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/child_process/ChildProcessTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/cluster/ClusterTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/console_module/ConsoleTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/console_module/ConsoleV8Test.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/crypto/CertificateTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/crypto/CryptoTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/dns/DNSAsyncTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/events/EventEmitterTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/fs/FsAsyncTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/fs/FsTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/fs/FsV8AsyncTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/fs/ReadStreamTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/http/HttpTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/http/StatusCodeTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/http2/Http2HeadersTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/net/NetTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/os/OSTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/path/PathTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/process/EnvironmentTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/process/ProcessTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/querystring/QueryStringTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/readline/ReadlineTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/tty/TTYTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/url/URLObjectTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/url/URLSearchParamsTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/url/URLTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/util/UtilTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/vm/VMTest.scala
  app/nodejs-v10/src/test/scala/io/scalajs/nodejs/zlib/ZlibTest.scala
Labels: chore

#149 Update sbt-release to 1.0.13
  project/plugins.sbt
Labels: chore
